export const questions = [
  { id: 'infiltratie', text: 'Na een regenbui trekt water de bodem van een grasveld in. Hoe heet dit?', options: ['Verdamping', 'Infiltratie', 'Condensatie', 'Verstening'], answer: 1, explanation: 'Infiltratie is het wegzakken van water in de bodem. Via poriën tussen bodemdeeltjes kan regenwater de grond in.' },
  { id: 'verstening', text: 'Een tuin met gras wordt helemaal betegeld. Wat gebeurt er bij dezelfde stevige regenbui?', options: ['Er infiltreert meer water en er stroomt minder weg.', 'Alle regen verdampt direct.', 'Er infiltreert minder water en er stroomt meer water over het oppervlak weg.', 'De tegels nemen al het regenwater op.'], answer: 2, explanation: 'Tegels laten meestal veel minder water door dan een grasveld. Door deze verstening stroomt meer water over het oppervlak naar bijvoorbeeld de straat en het riool.' },
  { id: 'keten', text: 'Een wijk krijgt meer asfalt en tegels. Welke keten van oorzaak en gevolg klopt bij een zware regenbui?', options: ['Meer verstening → minder infiltratie → meer afstroming → grotere kans op wateroverlast.', 'Meer verstening → meer infiltratie → minder afstroming → grotere kans op wateroverlast.', 'Meer verstening → minder regen → minder afstroming → grotere kans op wateroverlast.', 'Meer verstening → meer verdamping → geen water in het riool → altijd droge straten.'], answer: 0, explanation: 'Door verstening kan minder water de bodem in. Meer water stroomt snel naar laaggelegen plekken en het riool. Als de afvoer de hoeveelheid niet aankan, kan wateroverlast ontstaan.' },
  { id: 'maatregel', text: 'Een schoolplein heeft vaak grote plassen. Welke maatregel helpt regenwater lokaal in de bodem te laten zakken?', options: ['Het hele plein asfalteren.', 'Extra tegels boven op de oude tegels leggen.', 'Alle planten weghalen.', 'Een deel van de tegels vervangen door groen met een waterdoorlatende bodem.'], answer: 3, explanation: 'Groen met een waterdoorlatende bodem biedt ruimte voor infiltratie. Dat vermindert de hoeveelheid water die snel naar het riool stroomt. Hoe goed dit werkt, hangt ook af van de bodem en hoe nat die al is.' },
  { id: 'grens', text: 'Ook op een grasveld blijft na langdurige regen water staan. Wat is een goede verklaring?', options: ['Infiltratie vindt alleen plaats bij zonneschijn.', 'De bodem is al erg nat en kan het nieuwe regenwater niet snel genoeg opnemen.', 'Gras verandert regenwater in tegels.', 'Een onverhard oppervlak kan nooit wateroverlast hebben.'], answer: 1, explanation: 'Ook een onverharde bodem heeft grenzen. Als de bodem al erg nat is, of water langzaam doorlaat, kan nieuwe regen niet snel genoeg infiltreren. Daardoor kan ook daar water blijven staan.' },
];
export const topics = [
  { name: 'Weer & Klimaat', icon: '☀', description: 'Van wolken tot klimaatverschillen', active: false },
  { name: 'Water', icon: '≈', description: 'Infiltratie, verstening & wateroverlast', active: true },
  { name: 'Bevolking & Ruimte', icon: '⌂', description: 'Mensen en hun leefomgeving', active: false },
  { name: 'Examenskills', icon: '◎', description: 'Kaarten lezen en verbanden leggen', active: false },
];
